### ISSUE TITLE
clarify the pds-deep-archive submission process

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pdsen-operations#10]
After the initial submission done by operation team revise the procedure documentation

See ticket #6 when completed for feedback on initial submission.

**Comment by c-suh** [comment]
- original .zip delivery packages will not be posted or saved
- faulty packages will delivered via a new ticket which will be linked to from the original package's ticket
- faulty package files, if already posted, will not be removed as the differing timestamp/unique identifier will distinguish between the multiple submissions per data bundle
