### ISSUE TITLE
NSSDCA Delivery: urn:nasa:pds:msledl

### ISSUE THREAD

**Issue by Astro-Joni** [NASA-PDS/pdsen-operations#102]
## Discipline Node Information

ATM

[msledl_v1.0_NSSDCA_20210422.tar.gz](https://github.com/NASA-PDS/pdsen-operations/files/6359935/msledl_v1.0_NSSDCA_20210422.tar.gz)

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@Astro-Joni this set has been posted for NSSDCA processing. Beginning tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:msledl_v1.0_20210422

**Comment by smclaughlin7** [comment]
@Astro-Joni @c-suh  Hi, Joni. Our PDS4 front-end found a discrepancy for this submission, urn:nasa:pds:system_bundle:product_sip_deep_archive:msledl_v1.0_20210422. In particular, the bundle product [https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/msledl_bundle/bundle_msledl.xml ](url) does not correctly specify the MSL Spacecraft in the second instance of <Observing_System_Component>:
 
<Observing_System_Component>
   \<name>Accelerometer\</name>   _**<------ should be Mars Science Laboratory**_
   \<type>Instrument\</type>             _**<------ should be Spacecraft**_
   <Internal_Reference>
      <lid_reference>urn:nasa:pds:context:instrument_host:spacecraft.msl</lid_reference>
      <reference_type>is_instrument_host</reference_type>
   </Internal_Reference>
</Observing_System_Component>

The collection products, such as [https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/msledl_bundle/data/collection_msledl_data.xml](url), correctly specify the MSL spacecraft.

Could you/ATM please fix the bundle product then make and submit a new SIP?  Thanks!

**Comment by Astro-Joni** [comment]
I've updated and re-submitted.  Thanks all!

**Comment by smclaughlin7** [comment]
@Astro-Joni Thank you for fixing that bundle product and regenerating a new SIP as Issue #115.

**Comment by c-suh** [comment]
https://github.com/NASA-PDS/pdsen-operations/issues/115#issuecomment-849048787
