### ISSUE TITLE
NSSDCA Delivery: SBN-PSI Batch #13 (contains 2 resubmissions)

### ISSUE THREAD

**Issue by neese** [NASA-PDS/pdsen-operations#103]
## Discipline Node Information

**Delivering Node**: _please enter your DN here for record keeping purposes_
PDS_PSI

**NSSDCA Delivery Package**: _please upload the files output by PDS Deep Archive as a TAR.GZ or ZIP file here, or supply a URL to download from_
https://sbnarchive.psi.edu/pds4/deep_archive_deliveries/sbnpsi_batch_13_20210426.zip

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by neese** [comment]
This batch contains resubmissions of urn:nasa:pds:compil.satellite.colors::1.0 and urn:nasa:pds:gaskell.mimas.shape-model::1.0, plus 2 new bundles.

**Comment by c-suh** [comment]
@neese these sets have been posted for NSSDCA processing. Beginning tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LIDs below:

SIP LIDs:
urn:nasa:pds:system_bundle:product_sip_deep_archive:compil.satellite.colors_v1.0_20210426
urn:nasa:pds:system_bundle:product_sip_deep_archive:gaskell.mimas.shape-model_v1.0_20210426
urn:nasa:pds:system_bundle:product_sip_deep_archive:neowise_diameters_albedos_v1.0_20210426
urn:nasa:pds:system_bundle:product_sip_deep_archive:neowise_diameters_albedos_v2.0_20210426

**Comment by c-suh** [comment]
Archived:
- urn:nasa:pds:system_bundle:product_sip_deep_archive:compil.satellite.colors_v1.0_20210426
- urn:nasa:pds:system_bundle:product_sip_deep_archive:gaskell.mimas.shape-model_v1.0_20210426

---

Pre-Ingest:
- urn:nasa:pds:system_bundle:product_sip_deep_archive:neowise_diameters_albedos_v1.0_20210426
- urn:nasa:pds:system_bundle:product_sip_deep_archive:neowise_diameters_albedos_v2.0_20210426

**Comment by c-suh** [comment]
@neese the four sets from batch 13 have been archived.
