### ISSUE TITLE
NSSDCA Delivery: urn:nasa:pds:epoxi_mri::1.0

### ISSUE THREAD

**Issue by tbarnes4** [NASA-PDS/pdsen-operations#116]
## Discipline Node Information

**Delivering Node**: SBN/UMD

**NSSDCA Delivery Package**: https://pdssbn.astro.umd.edu/holdings/pds4-epoxi_mri-v1.0/SUPPORT/NSSDCA/

Please note that I manually edited the '*_sip_v1.0.xml' file to correct an [issue](https://github.com/NASA-PDS/pds-deep-archive/issues/99) with a wrong <aip_label_checksum> value being reported.  I was using pds-deep-archive 0.4.0

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tbarnes4 this set has been posted for NSSDCA processing. Beginning tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:epoxi_mri_v1.0_20210429
---
Regarding your comment: 

> Please note that I manually edited the '*_sip_v1.0.xml' file to correct an issue with a wrong <aip_label_checksum> value being reported. I was using pds-deep-archive 0.4.0

I'll spare you the long-windedness from my [other response](https://github.com/NASA-PDS/pdsen-operations/issues/117#issuecomment-831596197) and will simply state that we have recently released a [new version](https://github.com/NASA-PDS/pds-deep-archive/releases/tag/v1.0.0) of PDS Deep Archive which addresses the issue you mentioned above. Thank you for bringing it to our attention!

**Comment by c-suh** [comment]
This set is in pre-ingest

**Comment by c-suh** [comment]
@tbarnes4 this set has been archived!
