### ISSUE TITLE
[ldd-release] NucSpec LDD Version:1.0.0.0 IM Version:1.B.0.0

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS/pdsen-operations#12]
* **Is the LDD IngestLDD in Github?** Yes

* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** No

### Ingest LDD is in Github
* **Local Data Dictionary to Release**: https://github.com/pds-data-dictionaries/ldd-nucspec/tree/master/build/release/1.B.0.0/1.0.0.0
* **PDS4 IM version to release with**: 1.B.0.0
* **Need-by date**: 2020-09-30
* ** Need-by date rationale**: The GRaND team is migrating their data against this new dictionary.

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume._

**Comment by c-suh** [comment]
> PDS Validate Tool Report
> 
> Configuration:
>    Version                       1.24.0
>    Date                          2020-09-23T00:17:29Z
> 
> Parameters:
>    Targets                       [PDS4_NUCSPEC_1B00_1000.xml]
>    User Specified Schemas        [PDS4_NUCSPEC_1B00_1000.xsd]
>    User Specified Schematrons    [PDS4_NUCSPEC_1B00_1000.sch]
>    Severity Level                WARNING
>    Recurse Directories           true
>    File Filters Used             [*.xml, *.XML]
>    Data Content Validation       on
>    Product Level Validation      on
>    Max Errors                    100000
>    Registered Contexts File      /usr/local/validate-1.24.0/resources/registered_context_products.json
> 
> 
> 
> Product Level Validation Results
> 
>   PASS: file:/usr/local/validate-1.24.0/products/PDS4_NUCSPEC_1B00_1000/PDS4_NUCSPEC_1B00_1000.xml
>         1 product validation(s) completed
> 
> Summary:
> 
>   0 error(s)
>   0 warning(s)
> 
>   Product Validation Summary:
>     1          product(s) passed
>     0          product(s) failed
>     0          product(s) skipped
> 
>   Referential Integrity Check Summary:
>     0          check(s) passed
>     0          check(s) failed
>     0          check(s) skipped
> 
> 
> End of Report
> Completed execution in 3445 ms

**Comment by c-suh** [comment]
@jstone-psi NUCSPEC section added and files posted to https://pds.nasa.gov/datastandards/dictionaries/index.shtml#nucspec
