### ISSUE TITLE
[ldd-release] Particle LDD Version:2.0.0.0 IM Version:1.15.0.0

### ISSUE THREAD

**Issue by jmafi** [NASA-PDS/pdsen-operations#120]
* **Is the LDD IngestLDD in Github?** Yes
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** Yes
* **Need-by date**: 2021-05-07
* **Need-by date rationale**: Release of migrated product using Particle LDD v.2.0.0.0

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: https://github.com/pds-data-dictionaries/ldd-particle/tree/master/build/development/7e23bf9623fba8497d091ff6430ace65117106b5/1.15.0.0
* **PDS4 IM version to release with**: v.1.15.0.0

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

**Comment by jordanpadams** [comment]
@c-suh sorry for bumping this up in the list. it looks like this has a need-by date of end of week. hopefully we can sneak it in amongst all the other 1 million things you are working on :-)

**Comment by c-suh** [comment]
@jmafi and @jordanpadams, the files passed with the [latest version](https://github.com/NASA-PDS/validate/releases/v2.0.3) of the Validate tool and have been posted to the [PDS Data Dictionaries page](https://pds.nasa.gov/datastandards/dictionaries/index-1.15.0.0.shtml#particle). I am closing this ticket, but please let me know if I missed anything. Thank you!
