### ISSUE TITLE
NSSDCA Delivery: urn:nasa:pds:system_bundle:product_sip_deep_archive:insight_twins_v3.0_20210525

### ISSUE THREAD

**Issue by Astro-Joni** [NASA-PDS/pdsen-operations#125]
## Discipline Node Information

ATM

**NSSDCA Delivery Package**: 
[insight_twins_v3.0_20210525.tar.gz](https://github.com/NASA-PDS/pdsen-operations/files/6541226/insight_twins_v3.0_20210525.tar.gz)

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@Astro-Joni this set has been posted for NSSDCA processing. Beginning tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:insight_twins_v3.0_20210525

**Comment by c-suh** [comment]
Status: Pre-Ingest

**Comment by c-suh** [comment]
@Astro-Joni, this AIP/SIP set for insight_twins has been archived.
