### ISSUE TITLE
[ldd-survey] <Survey Dictionary> LDD Version:<1.0.1.0> IM Version:<1.15.0.0>

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS/pdsen-operations#129]
* **Is the LDD IngestLDD in Github?** Yes
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** Yes
* **Need-by date**: 6/30/21
* **Need-by date rationale**: The data provider for Spacewatch is building against 1F00.

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: https://github.com/pds-data-dictionaries/ldd-survey/tree/master/build/release/1.15.0.0
* **PDS4 IM version to release with**: 1.15.0.0/1F00

According to https://github.com/NASA-PDS/nasa-pds.github.io/wiki/B11.1-Beta-Testing#discipline-ldds, each new data dictionary will be released only for 1.16.0.0, but I would like for the new survey dictionary to be released for 1.15.0.0, as well, whenever this is doable.

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

**Comment by c-suh** [comment]
@jstone-psi, the Survey dictionary for 1F00 1010 has been validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index-1.15.0.0.shtml#survey.
