### ISSUE TITLE
[ldd-release] Survey LDD Version:1.0.0.0 IM Version:1.A.0.0

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS/pdsen-operations#13]
* **Is the LDD IngestLDD in Github?** Yes
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** No

### Ingest LDD is in Github
* **Local Data Dictionary to Release**: https://github.com/pds-data-dictionaries/ldd-survey/tree/master/build/release/1.A.0.0/1.0.0.0
* **PDS4 IM version to release with**: 1.A.0.0
* **Need-by date**: 2020-09-30
* ** Need-by date rationale**: Catalina Sky Survey will be releasing data for review by this date, and needs the LDD.

**Comment by c-suh** [comment]
> PDS Validate Tool Report
> 
> Configuration:
>    Version                       1.24.0
>    Date                          2020-09-23T00:21:10Z
> 
> Parameters:
>    Targets                       [PDS4_SURVEY_1A00_1000.xml]
>    User Specified Schemas        [PDS4_SURVEY_1A00_1000.xsd]
>    User Specified Schematrons    [PDS4_SURVEY_1A00_1000.sch]
>    Severity Level                WARNING
>    Recurse Directories           true
>    File Filters Used             [*.xml, *.XML]
>    Data Content Validation       on
>    Product Level Validation      on
>    Max Errors                    100000
>    Registered Contexts File      /usr/local/validate-1.24.0/resources/registered_context_products.json
> 
> 
> 
> Product Level Validation Results
> 
>   PASS: file:/usr/local/validate-1.24.0/products/PDS4_SURVEY_1A00_1000/PDS4_SURVEY_1A00_1000.xml
>         1 product validation(s) completed
> 
> Summary:
> 
>   0 error(s)
>   0 warning(s)
> 
>   Product Validation Summary:
>     1          product(s) passed
>     0          product(s) failed
>     0          product(s) skipped
> 
>   Referential Integrity Check Summary:
>     0          check(s) passed
>     0          check(s) failed
>     0          check(s) skipped
> 
> 
> End of Report
> Completed execution in 3495 ms

**Comment by c-suh** [comment]
@jstone-psi SURVEY section added and files posted to https://pds.nasa.gov/datastandards/dictionaries/index.shtml#survey
