### ISSUE TITLE
[ldd-release] <Clementine> LDD Version:<1.0.0.0> IM Version:<1.G.0.0>

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/pdsen-operations#131]
* **Is the LDD IngestLDD in Github?** _Yes_
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** _Yes_
* **Need-by date**: _June 24_
* **Need-by date rationale**: _Not an emergency -- just need to push release to facilitate Clementine PDS4 release_

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: _https://github.com/pds-data-dictionaries/ldd-clementine/releases/tag/1G00_1000_
* **PDS4 IM version to release with**: _1.G.0.0_

**Comment by c-suh** [comment]
@thareUSGS, this LDD has been validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#clementine.
