### ISSUE TITLE
[ldd-release] Spectral Discipline Dictionary LDD Version: 1.3.1.0 IM Version:1.16.0.0

### ISSUE THREAD

**Issue by acraugh** [NASA-PDS/pdsen-operations#133]
* **Is the LDD IngestLDD in Github?** _Yes_
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** _Yes_
* **Need-by date**: _31 July 2021_
* **Need-by date rationale**: _Data set going to review on June 30 will be delivering by end of July_

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: _https://github.com/pds-data-dictionaries/ldd-spectral/tree/master/build_
* **PDS4 IM version to release with**: _1G00, 1F00, 1E00_

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

**Comment by c-suh** [comment]
Hello @acraugh. The title mentions one IM version but three are listed in the description, so to clarify: you would like the following LDDs to be validated and posted?
- [PDS4_SP_1G00_1310](https://github.com/pds-data-dictionaries/ldd-spectral/releases/tag/1G00_1310)
- [PDS4_SP_1F00_1310](https://github.com/pds-data-dictionaries/ldd-spectral/releases/tag/1F00_1310)
- [PDS4_SP_1E00_1310](https://github.com/pds-data-dictionaries/ldd-spectral/releases/tag/1E00_1310)

**Comment by acraugh** [comment]
Yes, please!

**Comment by c-suh** [comment]
@acraugh, the three LDDs have been validated and posted to:
- [Data Dictionaries - 1.16.0.0](https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml#sp)
- [Data Dictionaries - 1.15.0.0](https://pds.nasa.gov/datastandards/dictionaries/index-1.15.0.0.shtml#sp)
- [Data Dictionaries - pre-1.15.0.0](https://pds.nasa.gov/datastandards/dictionaries/index-pre-1.15.0.0.shtml#sp)

**Comment by acraugh** [comment]
Thank you!

-Anne.

**Comment by c-suh** [comment]
@acraugh, you're welcome!
