### ISSUE TITLE
[ldd-release] ldd-insight LDD Version: 1900 IM Version: 1F00

### ISSUE THREAD

**Issue by sslavney** [NASA-PDS/pdsen-operations#134]
* **Is the LDD IngestLDD in Github?** Yes
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** Yes
* **Need-by date**: 2021-09-10
* **Need-by date rationale**: In time for validation of InSight Release 10 data on 2021-10-01

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: https://github.com/pds-data-dictionaries/ldd-insight/tree/master/build/release/1.15.0.0
* **PDS4 IM version to release with**: 1F00

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

**Comment by c-suh** [comment]
@sslavney, this LDD has been validated and posted to the LDDs page for [Mission Dictionaries](https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#insight).
