### ISSUE TITLE
[ldd-release] PDS4_MARS2020;  LDD Version 1000;  IM Version 1G00, 1F00, 1E00

### ISSUE THREAD

**Issue by sslavney** [NASA-PDS/pdsen-operations#137]
* **Is the LDD IngestLDD in Github?** yes
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** yes
* **Need-by date**:  July 30, 2021
* **Need-by date rationale**:  First deliveries of Mars 2020 data to PDS are due July 30, 2021, for release August 20, 2021. 

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: https://github.com/pds-data-dictionaries/ldd-mars2020/tree/main/build/release/1.16.0.0
* **PDS4 IM version to release with**: 1G00

* **Build directory of Local Data Dictionary to release**: https://github.com/pds-data-dictionaries/ldd-mars2020/tree/main/build/release/1.15.0.0
* **PDS4 IM version to release with**: 1F00

* **Build directory of Local Data Dictionary to release**: https://github.com/pds-data-dictionaries/ldd-mars2020/tree/main/build/release/1.14.0.0
* **PDS4 IM version to release with**: 1E00

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

**Comment by c-suh** [comment]
IM versions 1F00 and 1E00 have failed validation because it uses IMG schemas with LDD versions 1850 which are not posted on PDS. Creating tickets to address those first then will retry validation.

**Comment by c-suh** [comment]
@jordanpadams, is the procedure/documentation clear for these sorts of situations, i.e. using schemas that are not posted to PDS but available through GitHub? Is this why the MARS2020 GitHub repo (links above) includes the IMG schema files? Let me know if I shouldn't be validating and posting the required IMG schemas.

**Comment by jordanpadams** [comment]
@c-suh great question. our procedures do not include this. what needs to happen is if the LDD is dependent upon other versions of IMG LDDs, then those LDDs must be released first.

@thareUSGS @sslavney would you like us to release new versions of IMG to support mars2020 LDDs? see #138

**Comment by sslavney** [comment]
@jordanpadams and @c-suh what I would really like is to kick the IMG LDD out of the Mars 2020 LDD entirely, as it causes endless problems over which I have no control. Yes, please release whatever new versions of IMG LDD are necessary. It's not my dictionary though, so I guess you have to ask Myche or Trent.

**Comment by thareUSGS** [comment]
@sslavney @c-suh @jordanpadams I am still in a holding pattern with M2020 team on releasing an IMG update. The latest build version for testing is here: https://github.com/pds-data-dictionaries/ldd-img/tree/v1860_release 

It is primed for release, but trying to help the team with one more (a little complicated) ticket: https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/172

**Comment by jordanpadams** [comment]
@thareUSGS per our current release process, whenever we have the system build, we only release any updates for a discipline LDD for that particular system build. For instance, for IM Version 1.16.0.0 (1G00) we released [Imaging LDD v1850](https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml#img), but we do not release 1F00_1850 or 1E00_1850 unless explicitly requested through these Github tickets.

in order to support the release of this LDD, would you be OK with us releasing 1F00_1850 and 1E00_1850? They have already been tagged in the IMG repo, just not officially released online: https://github.com/pds-data-dictionaries/ldd-img/releases

**Comment by thareUSGS** [comment]
@jordanpadams I still think we are on hold (I don't have a final green light), but if you are willing to support 1F00, and 1E00 I am fine with that.

**Comment by jordanpadams** [comment]
@thareUSGS to clarify, we already released 1G00_1850, we are just asking if we can release that same IMG LDD for older versions of the IM.

any other updates to your LDD will need to be version 1860 anyways since we already released a 1850 (if that makes any sense. love all these versions flying around :-) )

**Comment by thareUSGS** [comment]
@jordanpadams I think I get it now. Yes for IMG, we only planned to release 1860 (working on that version for a while now). Almost ready for release - just need to check with Kate.

**Comment by jordanpadams** [comment]
@thareUSGS v1850 was released per https://github.com/pds-data-dictionaries/ldd-img/pull/111 and the issues we had with rebasing to master, etc. to confirm, can we release v1850 for the older versions of IMG? or do we need to pull those from online and re-generated Mar2020 LDD?

**Comment by jordanpadams** [comment]
@sslavney it looks like @thareUSGS is wrapping up some final changes on the IMG LDD v1860. would you still like to release this version of the M2020 LDD and then tag a new version when the new IMG LDD is available? or should we wait?

**Comment by sslavney** [comment]
@jordanpadams @thareUSGS I'd like to wait until IMG 1860 is available.

**Comment by c-suh** [comment]
@sslavney, IMG 1G00 1860 is now available (#145), but please note that this does not change the IMG LDDs available for IM versions [1F00](https://pds.nasa.gov/datastandards/dictionaries/index-1.15.0.0.shtml#img) and [1E00](https://pds.nasa.gov/datastandards/dictionaries/index-pre-1.15.0.0.shtml#img).

**Comment by sslavney** [comment]
@c-suh  I just re-submitted the Mars 2020 LDD for release, for IM version 1G00 only. I don't know how to make it work for 1F00 and 1E00. Please help.

**Comment by c-suh** [comment]
Hi @sslavney, would you like to include 1E00 and 1F00 with the new ticket for 1G00, similarly to how you did for this?

If not, re-submitting 1E00 and 1F00 separately is entirely okay.

If yes, near the top of the [new submission](https://github.com/NASA-PDS/pdsen-operations/issues/150), just beneath the title is the first comment/your description of the submission, boxed in light gray with a light gray bar at its top. In the top-right corner of that bar is a smiley face and three dots in a horizontal line; click the three dots and a dropdown appears, from which "Edit" is an option. From there, you can enter the information for 1F00 and 1E00.

Let me know if this has or has not been helpful!

**Comment by sslavney** [comment]
@c-suh Thanks. I added 1F00 and 1E00 to "PDS4 IM version to release with". I hope you can get it to work. When I tried running LDDtool locally on 1F00, it didn't work because it was trying to find PDS4_IMG_1E00_1860 and PDS4_IMG_1F00_1860, which don't exist.

**Comment by c-suh** [comment]
@sslavney, let's give it a try. I'll continue any further discussion on the new ticket at https://github.com/NASA-PDS/pdsen-operations/issues/150 and will close this one.
