### ISSUE TITLE
[ldd-request] Create new LDD "ebt"

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/pdsen-operations#139]
* **Local Data Dictionary Name:** Earth-Based Telescope

* **Namespace ID Requested:** ebt

* **Discipline or Mission LDD?** Discipline

* **Steward Organization Name:** PDS Small Bodies Node

* **LDD Steward Name:** Ben Hirsch

* **LDD Steward Email:** bhirsch1@umd.edu

* **LDD Stewardship Team Members:** Anne Raugh @acraugh, Ben Hirsch @benjhirsch

* **LDD Description:** This namespace will provide observing parameters, provenance, and geometry relevant to ground-based telescopes on Earth and for Earth-orbiting (or Lagrange point) telescopes

* **Rationale for creation of new LDD:** The types of calibration, filter descriptions, and geometry used in characterizing telescope data from these sources is inherently different from spacecraft-based observations. While there is some minor overlap in geometry concepts, the coordinates are typically two-dimensional (RA and Dec) or defined in FITS WCS, and thus are more aligned with the terminology and usage of astrophysics observatories than planetary orbiter/flyby missions. (Note that Anne Raugh (araugh@umd.edu) will be supporting the creation/configuration effort as needed.)

---

**Engineering Details**
- [x] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [x] Update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)

**Comment by c-suh** [comment]
Attempting to streamline procedures so the order is slightly off, e.g. namespace request has already been submitted and satisfied [here](https://github.com/NASA-PDS/pds4-information-model/issues/386).

**Comment by c-suh** [comment]
@jordanpadams, I've created the [LDD Stewardship Team](https://github.com/orgs/pds-data-dictionaries/teams/ebt-ldd-stewardship-team) but am unable to add @benjhirsch to it because he's not a member of [pds-data-dictionaries](https://github.com/orgs/pds-data-dictionaries/people). Which of the organization owners should I poke to add or invite him? I suppose I'm already bugging you about it, but for future cases?

**Comment by c-suh** [comment]
Status: Have created the repo, added teams with appropriate access, set branch protection, and cloned the PDS4 LDD Issue repo but haven't run the full script since the intended LDD steward is not yet a member of the pds-data-dictionaries organization and can't be assigned to any issues (Don't know how GitHub would handle a template with a non-member assignee, e.g. break or not register the assignee even after s/he becomes a member and require re-creating the template or other)

**Comment by acraugh** [comment]
Hi Catherine!

If it makes life easier you can set me as the steward ***@***.***) for the
repo for now, and we'll get Ben squared away with the repo later.  We
should practice transferring repo ownership anyway, since that's what would
happen with a mission namespace at end of mission.

-Anne.

**Comment by jordanpadams** [comment]
@c-suh congrats! you are now an Admin and can add Ben.

**Comment by c-suh** [comment]
@acraugh and @jordanpadams, great; thank you! I've invited @benjhirsch and will go ahead with Anne as the steward. Once Ben is settled in, we'll re-assign him to all future EBT issues.

**Comment by c-suh** [comment]
@pds-data-dictionaries/ebt-ldd-stewardship-team, your LDD repo is now ready for use at https://github.com/pds-data-dictionaries/ldd-ebt with Ben assigned as the steward.

**Comment by jordanpadams** [comment]
@c-suh looks like you cannot mention teams from other organizations. so can we update our procedure to include all users noted as part of the stewardship team?

@acraugh @benjhirsch ☝️

**Comment by jordanpadams** [comment]
@c-suh can we also update our "template message" to include a link to https://pds-data-dictionaries.github.io/getting-started.html#getting-to-know-your-ldd-repo for Getting to Know your LDD Repo ? ty!

**Comment by c-suh** [comment]
@jordanpadams, I was just looking at this and making sure I hadn't misstepped somewhere, so thank you for verifying! I will update the procedure for both those items.

---

@acraugh and @benjhirsch, please let me know if you would like to use the description above as is (taken from the namespace registry [request](https://github.com/NASA-PDS/pds4-information-model/issues/386)), or if you would like to modify it (recommended).

**Comment by acraugh** [comment]
Just curious - are we expecting mission stewards to use this repo, and if
so how does that impact the "team" structure?

-Anne.

**Comment by jordanpadams** [comment]
@acraugh 🤷‍♂️ . ideally mission stewards would use the same structures as discipline LDDs for consistency, but from the beginning of al the discussions regarding LDDs, we have taken the assumption that we will not impose anything on missions.

we can always create new teams for missions, but it is also public github so anyone can "watch" the repo, use the dictionaries, comment on tickets, create a pull requests, etc.

**Comment by acraugh** [comment]
Not really the point - I'm trying to figure out if I should be telling my
mission stewards to read the docs for the LDD repo and use it (instead of,
for example, having to install and run LDDTool locally).

-Anne.

**Comment by jordanpadams** [comment]
@acraugh copy. I think that is probably a case-by-case basis dependent upon the node and mission team? the more the merrier!
