### ISSUE TITLE
Forward old proposing pages to new web page

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pdsen-operations#141]
After trying to google for proposing to the PDS, it looks like our old web pages are still on line. Let's forward to the new web page:

https://pds.nasa.gov/home/proposers/proposing-programs.shtml -> https://pds.nasa.gov/home/proposers/
https://pds.nasa.gov/home/proposers/proposing-missions.shtml -> https://pds.nasa.gov/home/proposers/

**Comment by c-suh** [comment]
Redirected from the existing page.
