### ISSUE TITLE
[ldd-release] Particle LDD Version: 2.0.1.0 IM Version: 1.16.0.0

### ISSUE THREAD

**Issue by jmafi** [NASA-PDS/pdsen-operations#143]
* **Is the LDD IngestLDD in Github?** Yes
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** Yes
* **Need-by date**: 8/13/2021
* **Need-by date rationale**: Needed to support label design for a data archive currently in development

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: https://github.com/pds-data-dictionaries/ldd-particle/tree/main/build/release/1.16.0.0
* **PDS4 IM version to release with**: 1.16.0.0
* 
_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

**Comment by c-suh** [comment]
@jmafi, the files for PDS4_PARTICLE_1G00_2010 have been validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml#particle.
