### ISSUE TITLE
[ldd-request] Create new LDD "dart"

### ISSUE THREAD

**Issue by acraugh** [NASA-PDS/pdsen-operations#144]
* **Local Data Dictionary Name:**

Double Asteroid Redirection Test (DART) Mission Namespace

* **Namespace ID Requested:**

dart

* **Discipline or Mission LDD?** 

Mission namespace

* **Steward Organization Name:** 

For development, the steward JHU APL.
Once archived, the steward will be SBN.

* **LDD Steward Name:** 

For development, the steward is Ray Espitu, JHU APL.
SBN contact is Ben Hirsch and UMD; backup is Anne Raugh at UMD.

* **LDD Steward Email:** 
raymond.espirito@jhuapl.edu
bhirsch1@umd.edu
araugh@umd.ed

* **LDD Stewardship Team Members:** 

Same as stewards

* **LDD Description:**

This namespace provides classes specific to the NASA DART mission and, potentially, the concurrent LICIACube mission.

* **Rationale for creation of new LDD:**

Documentation of mission-specific metadata.

---

**Engineering Details**
- [x] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [x] Update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)

**Comment by acraugh** [comment]
Note that it is not necessary or even desired to create a repo for this mission namespace at this point. This just seems to be the only way to get the namespace registered...

**Comment by c-suh** [comment]
@acraugh, I've submitted a request to register the namespace and will keep you apprised of its status. Thank you for your patience amidst the changes as we optimize our procedures.

**Comment by acraugh** [comment]
Thanks @c-suh! We need to proceed with data ingest, so I'm going to make the potentially dangerous assumption that the namespace ID will be reserved.

If creating a repo now makes it easier to deal with this request, that's OK - I can at least "delivery" the Ingest_LDD to it.

**Comment by c-suh** [comment]
@acraugh, yes, I'll be creating a repo now lest I forget and cause a delay when it is needed. The namespace ID dart has been reserved, so do go ahead with data ingest. However, would you or Ray provide his GitHub username, please?

**Comment by acraugh** [comment]
@c-suh, Ray's Github handle is @RayEspiritu. We should both have access for the time being. Thanks!

**Comment by c-suh** [comment]
@acraugh, great; thank you! I will move ahead with the process, and you will soon be receiving notifications as such.

**Comment by c-suh** [comment]
@RayEspiritu, @benjhirsch, and @acraugh, your LDD repo is now ready for use at https://github.com/pds-data-dictionaries/ldd-dart. Read through [Getting to Know Your LDD Repo](https://pds-data-dictionaries.github.io/getting-started.html#getting-to-know-your-ldd-repo) to get started.
