### ISSUE TITLE
[ldd-release] <IMG> LDD Version:<1860> IM Version:<1G00>

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/pdsen-operations#145]
* **Is the LDD IngestLDD in Github?** _Yes_
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** _Yes_
* **Need-by date**: _ASAP - for Mars2020, sorry_
* **Need-by date rationale**: _Been on hold while Mars2020 has finished up their first review_

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: https://github.com/pds-data-dictionaries/ldd-img/releases/tag/1G00_1860
* **PDS4 IM version to release with**: _1G00. Other PDS IM's area available and can be released_

**Comment by c-suh** [comment]
@thareUSGS, the LDD for IMG 1G00 1860 has been validated and posted to the [PDS LDD page](https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml#img).

@sslavney, IMG 1G00 1860 is now available! Please note that the IMG LDDs for IM version [1F00](https://pds.nasa.gov/datastandards/dictionaries/index-1.15.0.0.shtml#img) and [1E00](https://pds.nasa.gov/datastandards/dictionaries/index-pre-1.15.0.0.shtml#img) have not been affected.
