### ISSUE TITLE
[ldd-release] <img_surface> LDD Version:<1260> IM Version:<1G00>

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/pdsen-operations#146]
* **Is the LDD IngestLDD in Github?** _Yes_
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** _Yes_
* **Need-by date**: _ASAP - for Mars2020, sorry_
* **Need-by date rationale**: _Been on hold while Mars2020 has finished up their first review_

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: https://github.com/pds-data-dictionaries/ldd-img_surface/releases/tag/1G00_1260
* **PDS4 IM version to release with**: _1G00. Other PDS IM's area available and can be released_

**Comment by c-suh** [comment]
@thareUSGS, this LDD has failed validation due to the following ([full report](https://github.com/NASA-PDS/pdsen-operations/files/6996454/PDS4_IMG_SURFACE_1G00_1260-validate-report.txt)):

```
  FAIL: file:PDS4_IMG_SURFACE_1G00_1260.xsd
      WARNING  [warning.label.schema]   line 25, 137: schema_reference.4: Failed to read schema document 'https://pds.nasa.gov/pds4/geom/v1/PDS4_GEOM_1G00_1930.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
      ERROR  [error.label.schema]   line 339, 85: src-resolve: Cannot resolve the name 'geom:Coordinate_Space_Reference' to a(n) 'element declaration' component.
    Begin Schema: https://pds.nasa.gov/pds4/geom/v1/PDS4_GEOM_1G00_1930.xsd
      FATAL_ERROR  [error.label.unresolvable_resource]   https://pds.nasa.gov/pds4/geom/v1/PDS4_GEOM_1G00_1930.xsd
    End Schema: https://pds.nasa.gov/pds4/geom/v1/PDS4_GEOM_1G00_1930.xsd
```

Please note that the latest LDD for GEOM is PDS4_GEOM_1G00_**1920** (full set available [here](https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml#geom).)

**Comment by thareUSGS** [comment]
@c-suh @jordanpadams hmm - looks like chicken/egg situation. I don't request PDS4_GEOM_1G00_1930 but github is building it for me and using as the default dependency...(?) I'm not sure how to lock a "release" build into PDS4_GEOM_1G00_1920? Or are there plans to officially release PDS4_GEOM_1G00_1930 and we can just wait a little? Not sure how to resolve this.

**Comment by jordanpadams** [comment]
@thareUSGS this is going to continue to be an issue for these off-nominal releases and I'm not sure there is a way we can fix it through the CICD in the near term. the continuous integration part is intended to make sure we don't break things when other LDDs change, but then for these off-nominal releases, it just throws all that out the window. it looks like some of the changes [made here to GEOM](https://github.com/pds-data-dictionaries/ldd-geom/pull/28) were for M2020, so maybe a release is necessary there as well? @mit3ch @edguinness thoughts?

 If you would like to build with the the older version of GEOM, you will need to generate the LDD manually.

**Comment by thareUSGS** [comment]
@c-suh I have compiled a manual release for PDS4_IMG_SURFACE_1G00_1260 which contains an updated dependency to PDS4_GEOM_1G00_1920 (from 1930).  This release will satisfy the current Mars2020 release (even if a new GEOM version is released soon).

[PDS4_IMG_SURFACE_1G00_1260.zip](https://github.com/NASA-PDS/pdsen-operations/files/7017421/PDS4_IMG_SURFACE_1G00_1260.zip)

**Comment by c-suh** [comment]
@thareUSGS, the files in the .zip passed validation and have been posted to the [PDS LDD page](https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml#img_surface). To complete the re-release of this LDD, please delete the existing 1G00_1260 release in the IMG_SURFACE repository before re-running the GitHub actions. Thank you!

**Comment by thareUSGS** [comment]
Thanks for checking and posting. Github "1260" releases deleted also.
