### ISSUE TITLE
NSSDCA Delivery: urn:nasa:pds:insight_ps

### ISSUE THREAD

**Issue by Astro-Joni** [NASA-PDS/pdsen-operations#148]
## Discipline Node Information

**Delivering Node**: ATM

**NSSDCA Delivery Package**: 
[insight_ps_v3.0_20210819.tar.gz](https://github.com/NASA-PDS/pdsen-operations/files/7016112/insight_ps_v3.0_20210819.tar.gz)

**Validation report**: 
[psval.txt](https://github.com/NASA-PDS/pdsen-operations/files/7016114/psval.txt)

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@Astro-Joni, the AIP/SIP set for insight_ps_v3.0 has been archived.
