### ISSUE TITLE
NSSDCA Delivery: urn:nasa:pds:insight_twins

### ISSUE THREAD

**Issue by Astro-Joni** [NASA-PDS/pdsen-operations#149]
## Discipline Node Information

**Delivering Node**: ATM

**NSSDCA Delivery Package**: 
[insight_twins_v3.0_20210819.tar.gz](https://github.com/NASA-PDS/pdsen-operations/files/7016130/insight_twins_v3.0_20210819.tar.gz)

**Validation report**: 
[insight_twins_v3.0_20210819.tar.gz](https://github.com/NASA-PDS/pdsen-operations/files/7016136/insight_twins_v3.0_20210819.tar.gz)
[twinsval.txt](https://github.com/NASA-PDS/pdsen-operations/files/7016137/twinsval.txt)

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@Astro-Joni, the AIP/SIP set for insight_twins_v3.0 has been archived.
