### ISSUE TITLE
Work with LDD Stewards to develop process and CCB

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pdsen-operations#15]

**Comment by tloubrieu-jpl** [comment]
@jordanpadams  who do you think that should be assigned to ?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl that was me

**Comment by jordanpadams** [comment]
@tloubrieu-jpl all tasks affiliated with this epic on me

**Comment by jordanpadams** [comment]
Tentative process defined at MC Tech Session: https://docs.google.com/presentation/d/1asZeIqixadn4iJqB2IQqGkpuTWdymrFwhvFRz4qCRoE/edit?usp=sharing
