### ISSUE TITLE
[ldd-release] Mars 2020 LDD Version:1000 IM Version:1G00, 1F00, 1E00

### ISSUE THREAD

**Issue by sslavney** [NASA-PDS/pdsen-operations#150]
* **Is the LDD IngestLDD in Github?** Yes
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** Yes
* **Need-by date**: August 20, 2021
* **Need-by date rationale**:  First release of Mars 2020 data

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**:  https://github.com/pds-data-dictionaries/ldd-mars2020/tree/main/build/release/1.16.0.0
* **PDS4 IM version to release with**: 1G00, 1F00, 1E00

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

### Latest LDD is NOT in Github
* **LDD**: _Name of LDD Ready for release_
* **LDD Submission Package (.zip)**: _zip consisting of the following files generated from LDDTool_
    * .xsd – XML Schema file
    * .sch – Schematron file
    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool

**Comment by c-suh** [comment]
https://github.com/NASA-PDS/pdsen-operations/issues/137#issuecomment-902120321

**Comment by c-suh** [comment]
@sslavney, I had missed the okay to post IMG 1F00 and 1E00 1860 but did so just now and all Mars 2020 LDDs have passed validation and been posted to the [Missions LDD page](https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#mars2020). The LDDTool should now also work for those two versions.

@jordanpadams, is the IngestLDD.xml a required file? Where in the repo would it sit, and should it be part of a release package? On an unrelated note, 10 of the 15 mission dictionaries have GitHub repos. I can add the relevant information (similarly to how we do for the discipline dictionaries), but what would you like written for the ones without a repo?

**Comment by sslavney** [comment]
Woo-hoo! I am so happy to have this done! Thanks very much, @c-suh !

**Comment by c-suh** [comment]
@sslavney, happy to be of service! If the presence of the IngestLDD.xml needs to be addressed, I will open a new ticket and notify you.
