### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:mars2020_moxie

### ISSUE THREAD

**Issue by Astro-Joni** [NASA-PDS/pdsen-operations#152]
## Discipline Node Information

**Delivering Node**: ATM

**NSSDCA Delivery Package**: 
[mars2020_moxie_v1.0_20210908.tar.gz](https://github.com/NASA-PDS/pdsen-operations/files/7131470/mars2020_moxie_v1.0_20210908.tar.gz)

**Validation report**: 
[moxieval.txt](https://github.com/NASA-PDS/pdsen-operations/files/7131592/moxieval.txt)

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@smclaughlin7, just verifying if there any errors with this set, similar to #151?

@Astro-Joni, please validate all future submissions with the appropriate Rule (explanation and examples are available in the Validate tool's documentation under "[Validation Rules](https://nasa-pds.github.io/validate/operate/index.html#Validation_Rules)").

**Comment by smclaughlin7** [comment]
@c-suh #152 is OK - Yay!

**Comment by Astro-Joni** [comment]
Catherine Suh ***@***.***> wrote:

>
***@***.***, just verifying if there any errors with this set, similar to #151?
>
***@***.***, please validate all future submissions with the appropriate Rule (explanation and examples are available in the Validate tool's documentation under "[Validation Rules](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnasa-pds.github.io%2Fvalidate%2Foperate%2Findex.html%23Validation_Rules&amp;data=04%7C01%7Cjojohnso%40astronomy.nmsu.edu%7C0f83f3bc53474200e34408d9749e6b9c%7Ca3ec87a89fb84158ba8ff11bace1ebaa%7C1%7C0%7C637669046024030722%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=zF5CfpRJE11f5mtFUX8FKc3j89J07C2EzoB1K7YLmBQ%3D&amp;reserved=0)"). 
>
>-- 

Hi all,

So I presume we need to re-run validation on the (slightly) improved
bundle?  I'll ask Lyle which rule he's been using when he does the
validation...he does the validation as part of the process when
we receive data.

Thanks.

Joni

**Comment by c-suh** [comment]
@Astro-Joni , the set for `mars2020_moxie` has been archived.
