### ISSUE TITLE
[ldd-release] Multi LDD Version: 2.0.0.0 IM Version: 1.16.0.0

### ISSUE THREAD

**Issue by jmafi** [NASA-PDS/pdsen-operations#153]
* **Is the LDD IngestLDD in Github?** Yes
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** Yes
* **Need-by date**: 2021-09-24
* **Need-by date rationale**: This version of this LDD is needed for a number of archives now in development.

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: https://github.com/pds-data-dictionaries/ldd-multi/tree/main/build/development/d771cdae51a6e190a784a5290b1924f94137a12c/1.16.0.0
* **PDS4 IM version to release with**: 1.16.0.0

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

**Comment by c-suh** [comment]
@jmafi, this LDD has been validated and posted to the [PDS Data Dictionaries page](https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml#multi).

**Comment by jordanpadams** [comment]
@jmafi can you please also tag this release in github first prior to submitting this request? that way everything is packaged as expected and officially released through github + on our website

https://pds-data-dictionaries.github.io/development/ldd-release.html#preparing-a-release

@c-suh can we check for this in our procedure?

**Comment by c-suh** [comment]
@jordanpadams, apologies and will do.
