### ISSUE TITLE
[ldd-release] MER LDD Version:1000 IM Version:1B00

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/pdsen-operations#160]
* **Is the LDD IngestLDD in Github?** No
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** Yes
* **Need-by date**: _Please indicate a drop-dead need-by date for this release_
* **Need-by date rationale**: _For quick turnarounds of releases, please indicate a rationale for the condensed schedule_

### Latest LDD is NOT in Github
* **LDD**: PDS4_MER_1B00_1000
* **LDD Submission Package (.zip)**: [PDS4_MER_1B00_1000.zip](https://github.com/NASA-PDS/pdsen-operations/files/7213938/PDS4_MER_1B00_1000.zip)
    * .xsd – XML Schema file
    * .sch – Schematron file
    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool

**Comment by c-suh** [comment]
This has failed validation due to the following:

>   FAIL: file:/PDS4_MER_1B00_1000/PDS4_MER_1B00_1000.xml
>       ERROR  [error.label.missing_file]   URI reference does not exist: file:/PDS4_MER_1B00_1000/ldd-mer-190827_MER_1000.xsd
>       ERROR  [error.label.missing_file]   URI reference does not exist: file:/PDS4_MER_1B00_1000/ldd-mer-190827_MER_1000.sch


Full report here: [PDS4_MER_1B00_1000-validate.txt](https://github.com/NASA-PDS/pdsen-operations/files/7213961/PDS4_MER_1B00_1000-validate.txt)

**Comment by jordanpadams** [comment]
FYI, it looks like the files referenced from the XML label refer to different file names than the XSD/SCH/etc. Updating the File_Area_XML_Schema should fix this issue.

**Comment by jennifergward** [comment]
Here is the revised XML label (renamed to .txt for file upload). Let me know if there's a better way to send it.
[PDS4_MER_1B00_1000.txt](https://github.com/NASA-PDS/pdsen-operations/files/7217905/PDS4_MER_1B00_1000.txt)

**Comment by c-suh** [comment]
@jennifergward, this was perfect! (Thank you for the workaround regarding the unsupported XML file type.) The LDD for `MER 1B00 1000` has been validated and posted to the [PDS Mission Data Dictionaries page](https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#mer).
