### ISSUE TITLE
[ldd-release] CTLI LDD version:1200 IM version:1E00

### ISSUE THREAD

**Issue by lylehuber** [NASA-PDS/pdsen-operations#18]
* **Is the LDD IngestLDD in Github?** Yes
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** Yes

### Ingest LDD is in Github
* **Local Data Dictionary to Release**: https://github.com/pds-data-dictionaries/ldd-ctli
* **PDS4 IM version to release with**:1E00
* **Need-by date**:N/A
* ** Need-by date rationale**: N/A

### Ingest LDD is NOT in Github

* **LDD**: _Name of LDD Ready for release_
* **LDD Submission Package (.zip)**: _ zip consisting of the following files generated from LDDTool:
    * .xsd – XML Schema file
    * .sch – Schematron file
    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume._

**Comment by c-suh** [comment]
NOTE: The LDD files were provided via email.

**Comment by c-suh** [comment]
@lylehuber, the files for CTLI 1E00 1200 have been posted to https://pds.nasa.gov/datastandards/dictionaries/#ctli.
