### ISSUE TITLE
[NSSDCA] urn:nasa:pds:insight-ifg-cruise::1.0

### ISSUE THREAD

**Issue by bharris-igpp** [NASA-PDS/pdsen-operations#2]
from PPI node.  If a delivery ID is needed, how about PPI_test-001_2020-07-14

[PPI_insight-ifg-cruise_test-1.zip](https://github.com/NASA-PDS/pdsen-operations/files/4922177/PPI_insight-ifg-cruise_test-1.zip)

**Comment by jordanpadams** [comment]
Thanks @bharris-igpp .

@elawsgh @c-suh I will take this one so I can write out the process

**Comment by jordanpadams** [comment]
@bharris-igpp the bundle has been submitted to the NSSDCA and is currently in processing.

**Comment by jordanpadams** [comment]
@bharris-igpp looks like we hit a snag delivering the bundle to NSSDCA because their system failed due to the "dangling" references to the InSight schemas and schematrons. Since this is a still a valid bundle, this is an issue that needs to be resolved by the NSSDCA, but just wanted to let you know in case you or the team wanted to update that.

**Comment by jordanpadams** [comment]
@bharris-igpp actually, here is a revised response from NSSDCA:

> As Tiffany noted the bundle and collection products for the Cruise-phase bundle (https://pds-ppi.igpp.ucla.edu/data/insight-ifg-cruise) definitely use the <insight:mision_pahse_name> element.  However those products for the Mars-phase bundle, for which we don’t yet have a SIP, do *not* presently use that element (https://pds-ppi.igpp.ucla.edu/data/insight-ifg-mars/) which is a bit inconsistent for a mission archive.

**Comment by jordanpadams** [comment]
> Hi PDS Operator, Jordan:
>  
> The NSSDCA has successfully ingested and archived the first PDS4 SIP:
>  
>      urn:nasa:pds:system_bundle:product_sip_deep_archive:insight-ifg-cruise_v1.0_20200714::1.1
>  
> You’re welcome to notify PPI and have them submit another bundle. 
>  
> As Tiffany noted yesterday, to view more detailed results for this SIP, use the PDS4 Reporting feature of our Planetary Submission Inteface (PSI) at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp and enter the SIP LIDVID in search box.  You can also enter the SIP LID to view results for all versions.  To view results for all SIPs, enter the partial LID string ‘urn:nasa:pds’.  I attached a screen shot of PSI’s report for this SIP.
>  
> Thanks for all your help, and PPI’s too!
