### ISSUE TITLE
[ldd-release] Dawn Mission Dictionary LDD Version:1.1.0.0 IM Version:1.B.0.0

### ISSUE THREAD

**Issue by jmafi** [NASA-PDS/pdsen-operations#21]
* **Is the LDD IngestLDD in Github?** Yes
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** Yes

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: https://github.com/pds-data-dictionaries/ldd-dawn/tree/master/build/1.B.0.0/1.1.0.0
* **PDS4 IM version to release with**: 1B00
* **Need-by date**: 10/31/2020
* **Need-by date rationale**: The GRaND instrument needs these updates to the DAWN dictionary in order to deliver their labels.

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

**Comment by c-suh** [comment]
@jmafi, validation shows the following 2 errors (shortened for readability):

>   FAIL: file:/validate-1.24.0/PDS4_DAWN_1B00_1100.xml
>       ERROR  [error.label.missing_file]   URI reference does not exist: file:/validate-1.24.0/ldd-dawn-s_DAWN_1100.xsd
>       ERROR  [error.label.missing_file]   URI reference does not exist: file:/validate-1.24.0/ldd-dawn-s_DAWN_1100.sch

The full report: [validate-report.txt](https://github.com/NASA-PDS/pdsen-operations/files/5393822/validate-report.txt)

---
**Note:** The error is caused by the .xml file _**inside the .zip file**_.

Please correct this whereupon we will try again. Thank you.

**Comment by c-suh** [comment]
Notified via external emails that the .zip file was corrected. Running validation.

**Comment by c-suh** [comment]
@jmafi, the files have been successfully validated with no errors and posted to the PDS [site](https://pds.nasa.gov/datastandards/dictionaries/#dawn).
