### ISSUE TITLE
Post PDS Data Dictionaries WebHelp to website with B11.0

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pdsen-operations#27]
@jshughes will work with @c-suh to get this posted to the website.

@c-suh will:
- [x] discuss where the WebHelp should be delivered prior to posting online
- [x] update release procedures to include posting WebHelp

**Comment by c-suh** [comment]
@jordanpadams the Data Standards' Documents main page on the test site is ready for review. The following changes pertain to the bullet point for PDS Common Data Dictionary:
- replace link for 'Current Release' to WebHelp (without LDDs)
- move 'Online Search' to new sentence in description
- add new link to WebHelp (with LDDs) to new sentence in description

**Comment by jshughes** [comment]
@jordanpadams just for clarification the WebHelp version linked to  "WebHelp format" was generated from the Common dictionary plus the current set of discipline LDDs. The addition of the discipline LDDs about doubled the size of the resulting DocBook file, the number of WebHelp files, and the time to generate the results. However, there were no other negative impacts.

**Comment by jordanpadams** [comment]
@c-suh @jshughes what do we think about adding a new "section" below "PDS Common Dictionary" for "PDS Local Data Dictionaries - Current Releases - All Releases - Online Search" similar to the way we have it in ops for "PDS Common Dictionary": https://pds.nasa.gov/datastandards/documents/ 

then for PDS Local Data Dictionaries:
* Current Releases  - links to https://pds.nasa.gov/datastandards/dictionaries/
* All Releases - links to https://pds.nasa.gov/datastandards/dictionaries/all-dictionaries.shtml 
* Online Search - links to the WebHelp

Thoughts?

---

Can we also update https://pds.nasa.gov/datastandards/dictionaries/ with a new sub-section below the `Data Dictionaries` header:

**Data Dictionary Search**
<link> Browse and search all data dictionary classes and attributes online. </link>


---

On a separate note, do we do anything at release time to actually update: https://pds.nasa.gov/tools/dd-search/ ? Or is that just whatever was populated years ago?

**Comment by jordanpadams** [comment]
@c-suh @jshughes open to any all comments on above.

**Comment by c-suh** [comment]
@jordanpadams from your suggested placement of the WebHelp link, I'm assuming it's for the WebHelp document which includes the LDDs. If the WebHelp **without** the LDDs will not be posted, should we forego even creating it as part of the release process?

I like the making the distinction between the Common and Local Data Dictionaries but will defer to your opinion and and @jshughes' on the exact placement of the WebHelp link. For now, I will go ahead with the proposed changes on the test site.

Regarding the addition to https://pds.nasa.gov/datastandards/dictionaries/, I have a few questions, but it'll be easier to show rather than to list them out.

I'll let you know once both pages are ready for review!

**Comment by jordanpadams** [comment]
@c-suh apologies this was not clear. coming up with mockup now. standby

**Comment by c-suh** [comment]
@jordanpadams I was just about to message! I've updated both pages (Data Standards: Documents and Data Standards: Data Dictionaries) on the test site. If helpful, feel free to use these as a reference or in lieu of the mockup.

**Comment by jordanpadams** [comment]
@c-suh looks good. a couple revisions:

* can we rework some of this directory structure? once we decide upon it, we are stuck with it forever. so let's try some of these directories:
   * dd/current/PDS4_PDS_DD_1F00-webhelp/index.html -> dd/current/PDS4_PDS_DD_1F00/webhelp/common/index.html
   * dd/current/PDS4_PDS_DD_1F00-webhelp/index.html -> dd/current/PDS4_PDS_DD_1F00/webhelp/all/index.html
* revise the description for the LDDs: `Discipline- and mission-specific class and attribute definitions for PDS4.`

Also, per this comment:
> If the WebHelp without the LDDs will not be posted, should we forego even creating it as part of the release process?

I'm not sure what you mean here since the **PDS Common Data Dictionary — Current Release** links to the webhelp? or am i missing something?

**Comment by c-suh** [comment]
> Also, per this comment:
> 
> > If the WebHelp without the LDDs will not be posted, should we forego even creating it as part of the release process?
> 
> I'm not sure what you mean here since the PDS Common Data Dictionary — Current Release links to the webhelp? or am i missing something?

@jordanpadams my apologies! I thought the suggested change was to revert the entirety of the Common Data Dictionary bullet point; that had 'Current Release' linked to the plain .html file, and I had forgotten to change it back.

I will keep that as is and implement the suggested directory changes. Please confirm that this would result in the following, using 1F00 files as an example:

.- PD4_DDS_DD_1F00/
.--- webhelp/
.------ all/
.--------- index.html
.------ common/
.--------- index.html
.- PD4_DDS_DD_1F00.html
.- PD4_DDS_DD_1F00.pdf

**Comment by jordanpadams** [comment]
made a few updates, but I think this is right.
> .- PDS4_PDS_DD_1F00/
> .--- webhelp/
> .------ all/
> .--------- index.html
> .------ common/
> .--------- index.html
> .- PDS4_PDS_DD_1F00.html
> .- PDS4_PDS_DD_1F00.pdf

**Comment by jordanpadams** [comment]
@c-suh ☝️

**Comment by c-suh** [comment]
Ah, yes, thank you for catching those. I've changed the directory structure and updated the definition for  the new LDD bullet point.

Data Dictionary's [All Releases](https://pds.nasa.gov/datastandards/documents/dd/) page will also need to be modified to include the new WebHelp. On the test site, I've added a linked option before `(.html) | (.pdf)`, or the link could be applied to the words before the dash, i.e. `Version 1 (1.15.0.0)`. Side note: the multiple sets of parentheses with pipes between seems awkward. Let me know if you would like this changed. @jshughes or @jordanpadams, any preference? 

---
> Can we also update https://pds.nasa.gov/datastandards/dictionaries/ with a new sub-section below the `Data Dictionaries` header:
> 
> Data Dictionary Search
> `link` Browse and search all data dictionary classes and attributes online. `/link`

@jordanpadams please review the page on the test site, as I've made a few changes (add section, add 2 items to the Table of Contents, make the Table of Contents sticky) but am not sure if this is what you had in mind.

---
> On a separate note, do we do anything at release time to actually update: https://pds.nasa.gov/tools/dd-search/ ? Or is that just whatever was populated years ago?

I wasn't able to find anything in the various process documentation.

**Comment by c-suh** [comment]
@jshughes If the directory structure for the WebHelp files as specified [above](https://github.com/NASA-PDS/pdsen-operations/issues/27#issuecomment-732464515) is agreeable, let me know if you would like me to svn commit or svn update those changes to the production machines.


@jordanpadams and @elawsgh, these pages ready for review. Please let me know if you would like these released for the imminent **B11.0**.
- [Documents](https://pds-gamma.jpl.nasa.gov/datastandards/documents/):
   - PDS Common Data Dictionary: changed "Current Release" link to that of the WebHelp format
   - Added a bullet point below the PDS Common Data Dictionary for PDS Local Data Dictionaries (has links to LDD latest releases, all releases, and the WebHelp format of the PDS Common + all Local Data Dictionaries)
- [Common Data Dictionary](https://pds-gamma.jpl.nasa.gov/datastandards/documents/dd/):
   - Changed "Version 1 (1.15.0.0)" from text to a link to the WebHelp format

**Comment by jshughes** [comment]
@c-suh The directory structure for the WebHelp files as specified is agreeable. Please feel free to update the production machines. I will update my local subversion directories. Sorry this is so late.

**Comment by c-suh** [comment]
The two are available from the the Data Standards' Documents [page](https://pds.nasa.gov/datastandards/documents/)
- [Common](https://pds.nasa.gov/datastandards/documents/dd/current/PDS4_PDS_DD_1F00/webhelp/common/)
- [Common + LDDs](https://pds.nasa.gov/datastandards/documents/dd/current/PDS4_PDS_DD_1F00/webhelp/all/)
