### ISSUE TITLE
[ldd-release] OREX LDD Version:1.4.0.0 IM Version:1.7.0.0

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS/pdsen-operations#29]
* **Is the LDD IngestLDD in Github?** No
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** Yes

### Latest LDD is NOT in Github
* **LDD**: OREX
* Note: The non-standard ldd filename has been approved for OSIRIS-REx by EN.

* **PDS4 IM version to release with**: 1.7.0.0
* **Need-by date**: 12/1/2020
* **Need-by date rationale**: This is the scheduled release date for OSIRIS-REx data that is supported by this dictionary.

[schema_1400.zip](https://github.com/NASA-PDS/pdsen-operations/files/5532107/schema_1400.zip)

**Comment by c-suh** [comment]
@jstone-psi and @neese, this LDD has been successfully validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index.shtml#orex.
