### ISSUE TITLE
Draft Discipline LDD CCB charter and Distribute for Review

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pdsen-operations#31]

**Comment by elawsgh** [comment]
Draft LCCB charter can be found here: https://docs.google.com/document/d/199RSYFg0zFlkdtjCSmHMqXg5Zkydm8IsLVmRF_KWqNI/edit#heading=h.32vhx6w5fz1e

Did the MC approve the establishment of this board?
Feel free to edit.

**Comment by jordanpadams** [comment]
@elawsgh this looks great! let's distribute to the stewards group and DDWG for review and input

**Comment by elawsgh** [comment]
Distributed draft for DDWG and stewards to review and provide input.
Target to finalize by end of 2010.

**Comment by jordanpadams** [comment]
done https://docs.google.com/document/d/1ecxlKzEVoOdRZ8ALrwA59wkz2M3-mk8asLUzLlSaz34/edit
