### ISSUE TITLE
Form LDD CCB with DN Support

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pdsen-operations#32]

**Comment by elawsgh** [comment]
Did the MC approve establishment of this LDD CCB?
If so, was it approved at the executive session?
Once the charter is finalized or closed to finalize, I will send email to MC mailing list to ask for member appointments.

**Comment by jordanpadams** [comment]
@elawsgh there was no official approval, but there was also no pushback. this ticket it intended to follow #31 where we draft a charter and get it approved. i was hoping you could help lead this effort? it should be eerily similar to the PDS4 CCB.

**Comment by elawsgh** [comment]
@jordanpadams 
I have drafted the LDD CCB charter, see the link in #31 . 
Please review and update.

**Comment by jordanpadams** [comment]
charter defined per #31. awaiting formation of group by MC.
