### ISSUE TITLE
[ldd-release] <CHAN1> LDD Version:<1.1.1.0> IM Version:<1.E.0.0>

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/pdsen-operations#35]
* **Is the LDD IngestLDD in Github?** _Yes_
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** _Yes_
* **Need-by date**: _Dec. 7, 2020_

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: https://github.com/pds-data-dictionaries/ldd-chan1/tree/master/build/release/1.E.0.0_1.1.1.0
* **PDS4 IM version to release with**: _1.E.0.0_

This release is to facilitate a PDS3 to PDS4 migration for M3 which @m-stclair is leading.

**Comment by c-suh** [comment]
@thareUSGS, the LDD has been successfully validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index.shtml#chan1.
