### ISSUE TITLE
[ldd-release] HYB2 LDD Version:1.0.0.0 IM Version:1.14.0.0

### ISSUE THREAD

**Issue by neese** [NASA-PDS/pdsen-operations#38]
* **Is the LDD IngestLDD in Github?** _Yes or no_ No
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** _Yes or no_ No
* **Need-by date**: _Please indicate a drop-dead need-by date for this release_ 1/4/2021
* **Need-by date rationale**: _For quick turnarounds of releases, please indicate a rationale for the condensed schedule_ We are expecting to release data referencing this dictionary on that date.

### Latest LDD is NOT in Github
* **LDD**: PDS4_HYB2_1E00_1000
* **LDD Submission Package (.zip)**: [hyb2_ldd-20201209.zip](https://github.com/NASA-PDS/pdsen-operations/files/5691361/hyb2_ldd-20201209.zip)
    * .xsd – XML Schema file
    * .sch – Schematron file
    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool

**Comment by c-suh** [comment]
Hi @neese. I've opened a ticket [here](https://github.com/NASA-PDS/pds4-information-model/issues/267) to add "HYB2" to the PDS namespace registry. Please fill in the description's last 2 bullet points for LDD Description and Rationale for creation of new LDD, and we will do our best to have it added and the LDD posted by the need-by date you specified above.

For reference, here are two other tickets requesting PDS namespace registry additions: [SURVEY](https://github.com/NASA-PDS/pds4-information-model/issues/234) and [chan1](https://github.com/NASA-PDS/pds4-information-model/issues/245).

**Comment by neese** [comment]
Hi Catharine, I didn't find those two bullets anywhere in the text form, so I filled in the information in free text.  Hope it is ok, if not just let me know what to do.

**Comment by c-suh** [comment]
Hi Carol, no worries and thank you for the information!

**Comment by c-suh** [comment]
@neese, the Hayabusa 2 namespace has been added to the namespace registry, and the LDD has been verified and posted to https://pds.nasa.gov/datastandards/dictionaries/#hyb2
