### ISSUE TITLE
Prepare Data Release Calendar for 2021

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/pdsen-operations#40]
Initial Excel sheet has been provided by David Hollibaugh, and information or verification has been requested from various nodes. Meanwhile, migrate the existing information and work on adding additional features, such as filtering by mission and released/unreleased data.

**Comment by jordanpadams** [comment]
@c-suh i believe this is done?

**Comment by c-suh** [comment]
@jordanpadams yes, sir, albeit not quite to satisfaction
