### ISSUE TITLE
NSSDCA Delivery: maven.spice, orex.spice, insight.spice, em16_spice

### ISSUE THREAD

**Issue by mcostasitja** [NASA-PDS/pdsen-operations#41]
## Overview

This delivery consists of a total of 40 SPICE Bundle products for MAVEN, Osiris Rex, Insight and ExoMars2016.
Given the number of outputs it has been agreed with Jordan H. Padams via personal communication, that the deliveries could be merged in a single issue. 

## Discipline Node Information

**Delivering Node**: NAIF

**NSSDCA Delivery Package**: https://naif.jpl.nasa.gov/pub/naif/pds/misc/nssdca/pds4/202012/
----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@mcostasitja, the link in the description for the delivery packages is returning a 404 (Not Found). Please update or provide another means of getting the multiple SPICE bundles. Thank you!

**Comment by mcostasitja** [comment]
@c-suh please note that I updated it this morning, the current one should work: https://naif.jpl.nasa.gov/pub/naif/pds/misc/nssdca/pds4/202012/

**Comment by c-suh** [comment]
@mcostasitja my apologies! Why I would refresh one page but not the other is beyond me. I will have a status for you shortly.

**Comment by mcostasitja** [comment]
@c-suh my bad, I should have notified you :)

**Comment by c-suh** [comment]
@mcostasitja no worries :)

This might take a little longer since it's my first go at a batch processing, but I will notify you before this Wednesday.

**Comment by c-suh** [comment]
@mcostasitja the bundles have been submitted to the NSSDCA and are currently in processing.

Using the SIP LID(s) below, you can check the status of this submission at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp.

SIP LID(s):
- urn:nasa:pds:system_bundle:product_sip_deep_archive:em16_spice_v1.0_20201219
- urn:nasa:pds:system_bundle:product_sip_deep_archive:em16_spice_v2.0_20201219
- urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v1.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v2.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v3.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v4.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v5.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v6.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v1.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v10.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v11.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v12.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v13.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v14.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v15.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v16.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v17.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v18.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v19.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v2.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v20.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v21.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v22.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v23.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v3.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v4.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v5.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v6.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v7.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v8.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v9.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:orex.spice_v1.0_20201219
- urn:nasa:pds:system_bundle:product_sip_deep_archive:orex.spice_v2.0_20201219
- urn:nasa:pds:system_bundle:product_sip_deep_archive:orex.spice_v3.0_20201219
- urn:nasa:pds:system_bundle:product_sip_deep_archive:orex.spice_v4.0_20201219
- urn:nasa:pds:system_bundle:product_sip_deep_archive:orex.spice_v5.0_20201219
- urn:nasa:pds:system_bundle:product_sip_deep_archive:orex.spice_v6.0_20201219
- urn:nasa:pds:system_bundle:product_sip_deep_archive:orex.spice_v7.0_20201219
- urn:nasa:pds:system_bundle:product_sip_deep_archive:orex.spice_v8.0_20201219
- urn:nasa:pds:system_bundle:product_sip_deep_archive:orex.spice_v9.0_20201219

**Comment by mcostasitja** [comment]
Perfect, thank you very much!

**Comment by c-suh** [comment]
@mcostasitja, a quick update: the **em16** bundles and **insight** bundles, excluding v6.0, have been ingested or archived. The others are still in processing.

Happy New Year!

**Comment by mcostasitja** [comment]
@c-suh thanks for the update.

Happy New Year!

**Comment by c-suh** [comment]
@mcostasitja 37 of the 40 bundles have been archived! I've indicated the status of the remaining 3 below.

---

Ingested:
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v23.0_20201218

Pre-ingest:
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v8.0_20201218
- urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v9.0_20201218

**Comment by mcostasitja** [comment]
Update noted!

**Comment by c-suh** [comment]
Notified through external email that all 40 bundles have been archived.
