### ISSUE TITLE
[ldd-release] OREX LDD Version: (Multiple) IM Version:(Multiple)

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS/pdsen-operations#42]
* **Is the LDD IngestLDD in Github?** No
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** Yes
* **Need-by date**: 1/22/2021

### Latest LDD is NOT in Github
* **LDD**: OREX
* **LDD Submission Package (.zip)**: _zip consisting of the following files generated from LDDTool_
    * .xsd – XML Schema file
    * .sch – Schematron file
    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool

Notes: This is an edit of the existing OREX dictionaries, to conform with the new LID formation rule proposed by Steve Hughes to resolve ambiguous LID references. These files contain edited and repackaged versions of the OREX dictonary files at https://pds.nasa.gov/datastandards/dictionaries/all-dictionaries.shtml. Only the LIDs have been changed. All other files and filenames have been preserved.
[orex_ldd_OREX_1400.zip](https://github.com/NASA-PDS/pdsen-operations/files/5789764/orex_ldd_OREX_1400.zip)
[Orex_schema_1300.zip](https://github.com/NASA-PDS/pdsen-operations/files/5789766/Orex_schema_1300.zip)
[PDS4_OREX_1700_1100.zip](https://github.com/NASA-PDS/pdsen-operations/files/5789767/PDS4_OREX_1700_1100.zip)
[PDS4_OREX_1700_1200.zip](https://github.com/NASA-PDS/pdsen-operations/files/5789768/PDS4_OREX_1700_1200.zip)

**Comment by jordanpadams** [comment]
@elawsgh @c-suh after we get the build out, can we get these updated ASAP?

**Comment by c-suh** [comment]
@jstone-psi and @jordanpadams these have been validated and updated at https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#orex
