### ISSUE TITLE
Make configuration changes to switch from SyBase to MySQL

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/pdsen-operations#44]
The majority of the database migration is being handled by Allan Yu; I am assisting in this one part.

---

At the moment, this is relevant to
- Dataset Status, and
- Resource Manager

**Comment by jordanpadams** [comment]
@c-suh what is the status of this here? is it complete? or was this our conversation about getting svn setup and running?

**Comment by jordanpadams** [comment]
waiting on alan to add username/password to mysql. code is ready for testing. able to build the WAR locally and run application.

**Comment by c-suh** [comment]
Changes were deployed to pds-gamma (on the 18th) and are undergoing testing

**Comment by c-suh** [comment]
Testing revealed this week that another change was required, and this change was deployed yesterday. There is now a permissions issue, but that is not related to the task specified in this ticket nor is it a matter in which I can assist, so this ticket is closed!
