### ISSUE TITLE
Update NSSDCA Delivery Procedure

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pdsen-operations#47]
Per the latest version of pds-deep-archive just released (v0.4.0), years are now included in the `manifest_url`, e.g.

**Before**: https://pds.nasa.gov/data/pds4/manifests/insight_documents_v2.0_20210125_sip_v1.0.tab
**Now**: https://pds.nasa.gov/data/pds4/manifests/2021/insight_documents_v2.0_20210125_sip_v1.0.tab

So we need to update our procedures for where to drop these files accordingly.

### Update Requested
Beginning with step 9 of the procedure, we need to update a few things:
* check the `manifest_url` in the SIP XML and verify if a year is included in the URL
* if it contains a year, copy the data to the appropriate year sub-directory under `manifests` (e.g. `manifests/2021`)
* if it does not contain a year, proceed with existing procedure, but notify user at end of process that a new version exists and they should upgrade at their earliest convenience. https://nasa-pds.github.io/pds-deep-archive/installation/index.html#upgrade-software

**Comment by jordanpadams** [comment]
@c-suh please verify my updates to the procedure make sense: https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@jordanpadams it looks good. I made a few small edits:
- make all examples reference the same bundle
- change first sentence of the comment in step 16
> As an additional note, PDS Deep Archive has been recently updated to v0.4.0, and it appears 
> you are using ~~a later~~ an earlier version.
- add a sentence to the first additional step clarifying what to do if the year is not included in the URL
- remove 2 steps (unrelated to this issue); this moved your additions to steps 7-9 and the later reference to the middle step was updated accordingly

---

Unrelated question regarding adding a Transfer Contact to https://nssdc.gsfc.nasa.gov/psi/: looking at the recent flow of emails to add Andrew for GEO, that seemed unnecessarily roundabout. Should this be folded into the delivery procedure as something along the lines of "Contact Stephanie with the name and node, and CC all involved parties and Jordan"?

**Comment by jordanpadams** [comment]
> Unrelated question regarding adding a Transfer Contact to https://nssdc.gsfc.nasa.gov/psi/: looking at the recent flow of emails to add Andrew for GEO, that seemed unnecessarily roundabout. Should this be folded into the delivery procedure as something along the lines of "Contact Stephanie with the name and node, and CC all involved parties and Jordan"?

Sounds great!
