### ISSUE TITLE
[ldd-release] (DISP,GEOM,SP) LDDs Version:(Multiple) IM Version:1.7.0.0

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS/pdsen-operations#48]
[ldd-release] (DISP,GEOM,SP) LDDs Version:(Multiple) IM Version:1.7.0.0

* **Need-by date**: 2/1/2021
* **Need-by date rationale**: OREx has a scheduled delivery this month, so it would be helpful if the dictionaries were updated ahead of the delivery.

Notes: This is an edit of the existing dictionaries that O-Rex depends on, to conform with the new LID formation rule proposed by Steve Hughes to resolve ambiguous LID references, similarly to #42. These files contain edited and repackaged versions of the DISP,GEOM, and SP dictionary files at https://pds.nasa.gov/datastandards/dictionaries/all-dictionaries.shtml. Only the LIDs have been changed. All other files and filenames have been preserved.
[PDS4_DISP_1700.zip](https://github.com/NASA-PDS/pdsen-operations/files/5876187/PDS4_DISP_1700.zip)
[PDS4_GEOM_1700_1401.zip](https://github.com/NASA-PDS/pdsen-operations/files/5876188/PDS4_GEOM_1700_1401.zip)
[PDS4_SP_1700.zip](https://github.com/NASA-PDS/pdsen-operations/files/5876189/PDS4_SP_1700.zip)

**Comment by c-suh** [comment]
The 3 LDDs have been validated and re-posted.
