### ISSUE TITLE
[ldd-release] (CTLI,DISP,GEOM,HYB2,IMG,SP) LDDs Version:(Multiple) IM Version:(Multiple)

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS/pdsen-operations#49]
[ldd-release] (CTLI,DISP,GEOM,HYB2,IMG,SP) LDDs Version:(Multiple) IM Version:(Multiple)

* **Need-by date**: 2/1/2021
* **Need-by date rationale**: Hayabusa2 is in liens resolution, and a quick update of these dictionaries would be helpful for that purpose

Notes: This is an edit of the existing dictionaries that Hayabusa2 depends on, to conform with the new LID formation rule proposed by Steve Hughes to resolve ambiguous LID references, similarly to #42. These files contain edited and repackaged versions of the CTLI,DISP,GEOM,HYB2,IMG,SP dictionary files at https://pds.nasa.gov/datastandards/dictionaries/all-dictionaries.shtml. Only the LIDs have been changed. All other files and filenames have been preserved.

[PDS4_CTLI_1E00_1200.zip](https://github.com/NASA-PDS/pdsen-operations/files/5876201/PDS4_CTLI_1E00_1200.zip)
[PDS4_DISP_1B00.zip](https://github.com/NASA-PDS/pdsen-operations/files/5876202/PDS4_DISP_1B00.zip)
[PDS4_GEOM_1E00_1810.zip](https://github.com/NASA-PDS/pdsen-operations/files/5876203/PDS4_GEOM_1E00_1810.zip)
[PDS4_HYB2_1E00_1000.zip](https://github.com/NASA-PDS/pdsen-operations/files/5876204/PDS4_HYB2_1E00_1000.zip)
[PDS4_IMG_1E00_1800.zip](https://github.com/NASA-PDS/pdsen-operations/files/5876205/PDS4_IMG_1E00_1800.zip)
[PDS4_SP_1E00_1300.zip](https://github.com/NASA-PDS/pdsen-operations/files/5876206/PDS4_SP_1E00_1300.zip)

**Comment by c-suh** [comment]
The 6 LDDs have been validated and re-posted. (First posting for PDS4_SP_1E00_1300.)

**Comment by jstone-psi** [comment]
@c-suh Are you saying that the SP dictionary wasn't already there? I'm pretty sure that I downloaded it from the data dictionary page.

Did you mean version 1.7.0.0 of SP, perhaps? (I think it didn't have a zip file.) It's not a big deal, but I just wanted to make sure that I didn't do something wrong.

**Comment by jstone-psi** [comment]
I see that there's also an entry for PDS4_SP_1F00_1300. Did PDS4_SP_1E00_1300 get replaced after I downloaded it? (I originally downloaded it on 1/15, in case that helps).

**Comment by c-suh** [comment]
@jordanpadams hm.. SP_1E00_1300 wasn't on the PDS site. https://github.com/pds-data-dictionaries/ldd-spectral/tree/master/build/release shows up to 1E00 (not 1F00), so I did a quick comparison of the SP_1F00_1300 files from https://pds.nasa.gov/datastandards/dictionaries/index-1.15.0.0.shtml#sp.

They've got the same timestamps, and the majority of the differences are purely the version numbers. The rest are from the xml:
`<logical_identifier>urn:nasa:pds:system_bundle:xml_schema:sp-xml_schema_1.14.0.0_1.3.0.0</logical_identifier>`
`<logical_identifier>urn:nasa:pds:system_bundle:xml_schema:sp-xml_schema</logical_identifier>`
and sch:
`<sch:assert test="@unit = ('Hz')">
    The attribute @unit must be equal to one of the following values 'Hz'</sch:assert>`
`<sch:assert test="@unit = ('GHz', 'Hz', 'MHz', 'THz', 'kHz', 'mHz')">
    The attribute @unit must be equal to one of the following values 'GHz', 'Hz', 'MHz', 'THz', 'kHz', 'mHz'.</sch:assert>`

**Comment by jstone-psi** [comment]
Ok, I just checked my metadata, and it says that I downloaded it from GitHub, so I think you are right. It still needs to be up there since this is the version that Hayabusa is using. It's strange that it wasn't up on the PDS website. And that also means that I don't know how they got a copy of this version.

This may not be an issue anymore, except for the fact that Hayabusa2 was somehow using an unpublished version.

**Comment by c-suh** [comment]
@jstone-psi. no apology necessary! I'm puzzled myself as to what happened. Jordan, let me know if you would like me to update or change something on the PDS site.

**Comment by jordanpadams** [comment]
@c-suh so if you go to https://github.com/pds-data-dictionaries/ldd-spectral/releases, [1E00](https://github.com/pds-data-dictionaries/ldd-spectral/releases/tag/1E00_1300) and [1F00](https://github.com/pds-data-dictionaries/ldd-spectral/releases/tag/1F00_1300) are both there? 1F00 doesn't show up on the home page because I did it manually and 1E00 came last (so Github assumes it is the latest).

For posting 1E00, as we talked about prior. that should go here: https://pds.nasa.gov/datastandards/dictionaries/index-pre-1.15.0.0.shtml . which is looks like you already did

**Comment by c-suh** [comment]
Ah, I see. I forgot that the releases page and build directory do not necessarily reflect each other. Thank you for the reminder and, yes, the PDS site should be up to date now with the SP LDDs.
