### ISSUE TITLE
Fix miscellaneous broken links for PDS site

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/pdsen-operations#54]
listed internally at the PDS Engineering site

**Comment by c-suh** [comment]
Waiting on link-checker to be run again (monthly?)

**Comment by tloubrieu-jpl** [comment]
Hi @c-suh , can you add an estimate for this ticket ? Thanks

**Comment by jordanpadams** [comment]
@c-suh @acyu-jpl where are we at with this? Is this a ticket? if so, can we elaborate in the details of what and when this needs to happen?

**Comment by c-suh** [comment]
@tloubrieu-jpl @jordanpadams @acyu-jpl sorry for the huge delay. This is potentially a recurring task, but I don't see this being the case as there aren't many additions to the PDS site. As Allan suggested in the email, this ticket can be closed and a new one opened if the next run of the link checker shows enough broken links to warrant it.
