### ISSUE TITLE
[ldd-release] MAVEN LDD Version: 1.1.1.0 IM Version:1.13.0.0

### ISSUE THREAD

**Issue by jmafi** [NASA-PDS/pdsen-operations#68]
* **Is the LDD IngestLDD in Github?** Yes
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** Yes
* **Need-by date**: 2021-02-26
* **Need-by date rationale**: Update required for MAVEN data products released on 2021-02-16

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: ~~https://github.com/pds-data-dictionaries/ldd-mvn/tree/V1110-EM5-release/build~~ https://github.com/pds-data-dictionaries/ldd-mvn/releases/tag/1D00_1110
* **PDS4 IM version to release with**: 1.13.0.0

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

**Comment by c-suh** [comment]
@jmafi the files have been validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#mvn. Have a great weekend!
