### ISSUE TITLE
NSSDCA Delivery: SBN-PSI Batch 4 Resubmit

### ISSUE THREAD

**Issue by neese** [NASA-PDS/pdsen-operations#83]
## Discipline Node Information

**Delivering Node**: _please enter your DN here for record keeping purposes_
PDS_PSI

**NSSDCA Delivery Package**: _please upload the files output by PDS Deep Archive as a TAR.GZ or ZIP file here, or supply a URL to download from_
https://sbnarchive.psi.edu/pds4/deep_archive_deliveries/sbnpsi_batch_4_20210312.zip
----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@neese these sets have been posted for NSSDCA processing. Beginning tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID(s) below:

SIP LID(s):
urn:nasa:pds:system_bundle:product_sip_deep_archive:ladee_ldex_v1.0_20210312
urn:nasa:pds:system_bundle:product_sip_deep_archive:ladee_ldex_v1.1_20210312
urn:nasa:pds:system_bundle:product_sip_deep_archive:ladee_ldex_v1.2_20210312

**Comment by c-suh** [comment]
Status: 
- Archived: v1.0 and v1.2
- Pre-Ingest: v1.1

**Comment by c-suh** [comment]
v1.1 still pre-ingest

**Comment by c-suh** [comment]
v1.1 status: Pre-ingest
(other 2 - v1.0 and v1.2 - are Archived)

**Comment by c-suh** [comment]
status: same

**Comment by c-suh** [comment]
@neese all sets have been archived!

**Comment by smclaughlin7** [comment]
Hi Carol,
Thank you. The LADEE LDEX V1.0 and 1.1 bundles popped up when I was doing some recent ingest integrity checks, but I totally forgot that back in August we agreed on the solution you described above.  My mistake!  I'll record a note about these bundles for future integrity checks.  Thanks again!  @neese @jordanpadams @c-suh
