### ISSUE TITLE
[ldd-release] GEOM LDD Version:1810 IM Version:1E00

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pdsen-operations#9]
* **Is the LDD IngestLDD in Github?** _no_

### Ingest LDD is NOT in Github
[GEOM_1E00_1810.zip](https://github.com/NASA-PDS/pdsen-operations/files/5195730/GEOM_1E00_1810.zip)

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume._

Submitted by @edguinness

**Comment by c-suh** [comment]
renamed .zip and folder to be conformant with PDS naming standards, i.e. PDS4_GEOM_1E00_1810

**Comment by c-suh** [comment]
https://pds.nasa.gov/datastandards/dictionaries/#geom and https://pds.nasa.gov/datastandards/dictionaries/all-dictionaries.shtml#geom have been updated.

@jordanpadams any verification required from any parties before we close this issue and active development can resume?

**Comment by jordanpadams** [comment]
@c-suh yes. please contact @edguinness to send a confirmation here

**Comment by c-suh** [comment]
Hi @edguinness. We've updated the GEOM LDDs at https://pds.nasa.gov/datastandards/dictionaries/#geom and https://pds.nasa.gov/datastandards/dictionaries/all-dictionaries.shtml#geom. Please review and let us know with a comment on this issue if all is well or if there are any problems.

**Comment by edguinness** [comment]
Hi, I looked at the PDS web site entry for the Geom dictionary. I see that the zip file includes the ingest file (ingest-pds4_geom_1e00_1810.xml). I don't think that needs to be included. Jordan may want to put it on GitHub, however.

**Comment by c-suh** [comment]
@jordanpadams please advise on availability and placement of the ingest file.

**Comment by jordanpadams** [comment]
@edguinness we have actually been including the ingestLDD as much as possible in the ZIP files since they have become such an important part of the dictionary development process. if a user doesn't need it, they can toss it, but until it has been determined what is "archival" and what is not, we figured we would put the kitchen sink in there.

thoughts?

**Comment by jordanpadams** [comment]
Per offline emails, @c-suh we are go for 🚀
